---

image: registry.gitlab.com/vpnbeast/docker-images/docker-base:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - build


test:
  stage: test
  script:
    - mvn clean verify -B
  rules:
    - if: $CI_MERGE_REQUEST_ID # Execute jobs in merge request context

build:
  stage: build
  before_script:
    - chmod +x ci-scripts/build.sh
    - chmod +x ci-scripts/release.sh
  script:
    - /bin/sh ci-scripts/build.sh
    - /bin/sh ci-scripts/release.sh
  rules:
    - if: $CI_COMMIT_BRANCH == 'master' # Execute jobs when a new commit is pushed to master branch